rootProject.name = 'unblu-middleware-lib'

include 'unblu-middleware-lib-bom'
include 'unblu-middleware-lib-core-common'
include 'unblu-middleware-lib-core-webhooks'
include 'unblu-middleware-lib-core-outboundrequests'
include 'unblu-middleware-lib-core-dialog-bot'
include 'unblu-middleware-lib-core-conversation-observing-bot'
include 'unblu-middleware-lib-core-external-messenger'
include 'unblu-middleware-lib-spring-common'
include 'unblu-middleware-lib-spring-webhooks'
include 'unblu-middleware-lib-spring-outboundrequests'
include 'unblu-middleware-lib-spring-dialog-bot'
include 'unblu-middleware-lib-spring-conversation-observing-bot'
include 'unblu-middleware-lib-spring-external-messenger'
include 'unblu-middleware-lib-quarkus-common'
include 'unblu-middleware-lib-quarkus-webhooks'
include 'unblu-middleware-lib-quarkus-outboundrequests'
include 'unblu-middleware-lib-quarkus-dialog-bot'
include 'unblu-middleware-lib-quarkus-conversation-observing-bot'
include 'unblu-middleware-lib-quarkus-external-messenger'
include 'unblu-middleware-lib-quarkus-deployment'
include 'unblu-middleware-lib-quarkus-integration-tests'
